spring.application.name=FoodApp-Backend


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=HiUdayKumarDaidaThisIsASecretKeyForJWTBackend
jwt.expiration=86400000

spring.cache.type=redis

spring.data.redis.host=redis-cache
spring.data.redis.port=6379


razorpay.key=rzp_test_SpX49oVNndzrZp
razorpay.secret=740xKCLXYLAJcJShCKUAc5wn